### ISSUE TITLE
Powerpoint Presentation

### ISSUE THREAD

**Issue by chelseathroop** [chelseathroop/UUVCapstone#2]
Powerpoint presentation template has been uploaded. Please make a look and update with your information. Be sure to be careful with pulling from repository before making any changes and commit and push when you are finished.

**Comment by keyaee** [comment]
Hey Chelsea,I am not finding powerpoint presentation template. Can u pls let me know where did u upload in the github.... 

```
 On Thursday, January 22, 2015 2:03 PM, chelseathroop <notifications@github.com> wrote:
```

 Powerpoint presentation template has been uploaded. Please make a look and update with your information. Be sure to be careful with pulling from repository before making any changes and commit and push when you are finished.—

**Comment by tconantpdx** [comment]
Its in UUVCapstone/CapstoneAssignements/CapstoneProposal.pptx
https://github.com/chelseathroop/UUVCapstone/blob/431e2cbc5a423524924b0ec507e0f930acfe22de/CapstoneAssignments/CapstoneProposal.pptx

Here
https://github.com/chelseathroop/UUVCapstone/tree/431e2cbc5a423524924b0ec507e0f930acfe22de/CapstoneAssignments
is a link.

Trevor

**Comment by chelseathroop** [comment]
Thank you Trevor. Sorry I should have included a link.
